# Generated by Django 4.1.3 on 2022-12-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('EmployeeImage', models.CharField(max_length=100)),
                ('DepartementName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.departement')),
            ],
        ),
    ]
